default: &default
  adapter: postgresql
  encoding: unicode
  pool: 20

development:
  <<: *default
  database: <%= ENV.fetch('DB_NAME') %>
  username: <%= ENV.fetch('USERNAME') %>
  password: <%= ENV.fetch('PASSWORD') %>
  host: <%= ENV.fetch('HOSTNAME') %>
  port: <%= ENV.fetch('PORT').to_i %>

test:
  <<: *default
  username: postgres
  password: ""
  database: lovechoice_test
  host: db

production:
  <<: *default
  database: lovechoice
  username: app
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>
