default: &default
  adapter: postgresql
  encoding: unicode
  pool: 20

development:
  <<: *default
  username: postgres
  password: ""
  database: lovechoice_dev
  host: db

test:
  <<: *default
  username: postgres
  password: ""
  database: lovechoice_test
  host: db

production:
  <<: *default
  database: lovechoice
  username: app
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>
